#!/bin/sh
# -----------------------------------------
# OpenOffice wrapper script for OpenOffice.org
# -----------------------------------------
# (based on Mandrake & Red Hat & Debian)

OOVERSION=@OOVERSION@
OOVERSIONRC="$HOME/.sversionrc"

if [ ! -z "$CONFIG_DIR" ]; then
    OOHOME="$HOME/$CONFIG_DIR/openoffice"
else
    OOHOME="$HOME/.openoffice"
fi

# Remove any entry in .sversionrc if not already installed from RPM
if [ -f "$OOVERSIONRC" ]; then
  oohome=$(cat $OOVERSIONRC | tr '\r' '\n' | grep "^OpenOffice.org ${OOVERSION}" |  sed "s|^OpenOffice.org ${OOVERSION}=file://||")
  if [ -n "$oohome" -a "$oohome" != "$OOHOME" ]; then
    cp $OOVERSIONRC $OOVERSIONRC.orig
    perl -ni -e "m|file://${oohome}| or print" $OOVERSIONRC
  fi
fi

# Issue a workstation-type installation for the user, if necessary
echo -n "Checking for existing user installation... "
if [ -d "$OOHOME" ] && [ -e "$OOHOME/soffice" ] && [ -e "$OOHOME/spadmin" ] ; then
  echo "FOUND"
else
  echo "NOT FOUND"
  echo -n "Performing first-time installation for user... "
  # rename old .sversonrc
  [ -f $HOME/.sversionrc ] && mv $HOME/.sversionrc $HOME/.sversionrc.old
  # run the automated setup
  lang=$(eval $(locale); echo "$LC_MESSAGES" | sed -n "s/\([a-z]*\)_.*/\1/p")
  /usr/lib/openoffice/program/setup -R:/etc/openoffice/autoresponse.conf -d:$OOHOME
  cat > $OOHOME/user/registry/data/org/openoffice/Setup.xcu << EOF
<?xml version="1.0" encoding="UTF-8"?>
<oor:component-data xmlns:oor="http://openoffice.org/2001/registry" xmlns:xs="http://www.w3.org/2001/XMLSchema" oor:name="Setup" oor:package="org.openoffice">
 <node oor:name="Office">
  <prop oor:name="ooSetupInstallPath" oor:type="xs:string">
   <value>$OOHOME/user</value>
  </prop>
 </node>
 <node oor:name="L10N">
  <prop oor:name="ooLocale" oor:type="xs:string">
   <value>$lang</value>
  </prop>
 </node>
</oor:component-data>  
EOF
  echo "DONE"
fi

echo "Starting OpenOffice.org..."
LANG=$lang
export LANG
exec $OOHOME/soffice "$@"
