#!/bin/sh
# -----------------------------------------
# OpenOffice wrapper script for OpenOffice.org
# -----------------------------------------
# (based on Mandrake & Red Hat)

OOVERSION=@OOVERSION@
OOVERSIONRC="$HOME/.sversionrc"
OOHOME="$HOME/.openoffice"

# Remove any entry in .sversionrc if not already installed from RPM
if [ -f "$OOVERSIONRC" ]; then
  oohome=$(cat $OOVERSIONRC | tr '\r' '\n' | grep "^OpenOffice.org ${OOVERSION}" |  sed "s|^OpenOffice.org ${OOVERSION}=file://||")
  if [ -n "$oohome" -a "$oohome" != "$OOHOME" ]; then
    cp $OOVERSIONRC $OOVERSIONRC.orig
    perl -ni -e "m|file://${oohome}| or print" $OOVERSIONRC
  fi
fi

# Issue a workstation-type installation for the user, if necessary
echo -n "Checking for existing user installation... "
if [ -d "$OOHOME" ] && [ -e "$OOHOME/soffice" ] && [ -e "$OOHOME/spadmin" ] ; then
  echo "FOUND"
else
  echo "NOT FOUND"
  echo -n "Performing first-time installation for user... "
  # rename old .sversonrc
  [ -f $HOME/.sversionrc ] && mv $HOME/.sversionrc $HOME/.sversionrc.old
  # run the automated setup
  lang=$(eval $(locale); echo "$LC_MESSAGES" | sed -n "s/\([a-z]*\)_.*/\1/p")
  if [ -n "$lang" -a -e "/usr/lib/openoffice/help/${lang%%%%_*}" ]; then
    /usr/lib/openoffice/program/setup -R:/etc/openoffice/autoresponse.conf -LANG:$lang
  else
    /usr/lib/openoffice/program/setup -R:/etc/openoffice/autoresponse.conf
  fi
  echo "DONE"
fi

# Fix up English wordbook (check dictionary.lst because user may have
# removed en_US dictionary afterward)
if [ ! -e "$OOHOME/user/wordbook/dictionary.lst" ]
then
(cd $OOHOME/user/wordbook;
  for file in /usr/lib/openoffice/share/wordbook/english/en_US.???; do
    ln -s $file .
  done
  echo "DICT en US en_US" > dictionary.lst
)
fi

# Register localized dictionary
# (dictionary.lst is bound to exist, see above)
lang=$(sed -n "/LC_MESSAGES=\([a-z]*_[A-Z]*\).*/s//\1/p" /etc/sysconfig/i18n)
if ! grep -q "$lang" "$OOHOME/user/wordbook/dictionary.lst"; then
  if [ -f "/usr/lib/myspell/$lang.aff" ]; then
  (cd $OOHOME/user/wordbook;
    for file in /usr/lib/myspell/$lang.???; do
      ln -sf $file .
    done
    echo "DICT ${lang%%_*} ${lang##*_} $lang" >> dictionary.lst
  )
  fi
fi

# Expand TrueType and Type1 font paths
chkfontpath="/usr/sbin/chkfontpath"
if [ -x "$chkfontpath" ]; then
  fontpath=$($chkfontpath | perl -ne '/[0-9]+: (.*)/ and print "$1;"')
else
  ttf_fontpath="/usr/share/fonts/TTF;/usr/share/fonts/default/TrueType"
  for fontdir in /usr/share/fonts/ttf/*; do
    ttf_fontpath="$ttf_fontpath;$fontdir"
  done
  type1_fontpath="/usr/share/fonts/Type1;/usr/share/fonts/default/Type1"
  fontpath="$ttf_fontpath;$type1_fontpath"
fi
SAL_FONTPATH_USER="$fontpath;$SAL_FONTPATH_USER"

# Get rid of broken Japanese fonts for now
SAL_FONTPATH_USER=$(echo "$SAL_FONTPATH_USER" | sed -e "s|/usr/share/fonts/ja/TrueType;||g")

# Get rid of broken Chinese fonts for now
SAL_FONTPATH_USER=$(echo "$SAL_FONTPATH_USER" | sed -e "s|/usr/share/fonts/zh_TW/TrueType;||g")

export SAL_FONTPATH_USER
echo "Starting OpenOffice.org..."
exec $OOHOME/soffice "$@"
